- name: working on conditions part
  hosts: localhost
  tasks:
    - name: apple price
      ansible.builtin.debug:
        msg: Price of fruit apple is - 100
      when: fruit == "Apple"

    - name: Orange price
      ansible.builtin.debug:
        msg: Price of fruit orange is - 100
      when: fruit == "Orange"

- name: Demo on conditions
  hosts: localhost
  tasks:
    - name: Print Apple Price
      ansible.builtin.debug:
        msg: Apple fruit Price is - 1$
      when: fruit == "apple"

    - name: Print Orange Price
      ansible.builtin.debug:
        msg: Orange fruit Price is - 2$
      when: fruit == "orange"
