- name: Example of parameter
  hosts: all
  tasks:
    - name: to get parameter store
      ansible.builtin.debug:
        msg: "{{ lookup('amazon.aws.aws_ssm', 'ansible_parameter', region='us-east-1' ) }}"