- name: Practice Print statement
  hosts: localhost
  tasks:
    - name: print my name
      ansible.builtin.debug:
        msg: My name is Varnita Rajesh Fagade

- name: Practice task level variable
  hosts: localhost
  vars:
    NAME: VARNITA RAJEH FEGADE
  tasks:
    - name: task level
      ansible.builtin.debug:
        msg: "{{ NAME }}"
      vars:
          NAME: Mrunmayi Fegade

    - name: Practice play level variable
      ansible.builtin.debug:
        msg: "{{ NAME }}"

- name: Practice task level variable
  hosts: localhost
  roles:
    - demo


